### ISSUE TITLE
Numpy 2 breaks reading scalar datasets as binary

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5grove#94]
I've set up a fresh dev environment with Python 3.12.2 and I'm getting the error below when fetching scalar datasets as binary:

```
Uncaught exception GET /data/?file=sample.h5&path=%2Fint8_scalar&format=bin&dtype=safe (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/data/?file=sample.h5&path=%2Fint8_scalar&format=bin&dtype=safe', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/users/me/.pyenv/versions/3.12.2/lib/python3.12/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/h5grove/h5grove/tornado_utils.py", line 49, in get
    response = self.get_response(
               ^^^^^^^^^^^^^^^^^^
  File "/home/me/h5grove/h5grove/tornado_utils.py", line 90, in get_response
    response = self.get_content_response(content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/h5grove/h5grove/tornado_utils.py", line 122, in get_content_response
    return encode(data, format_arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/h5grove/h5grove/encoders.py", line 114, in encode
    content_array = np.array(content, copy=False)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.
```

The following dependency versions are installed:

```
h5py              3.11.0
numpy             2.0.0
orjson            3.10.6
pip               24.0
tifffile          2024.7.24
tornado           6.4.1
typing_extensions 4.10.0
```

If I downgrade numpy to 1.x, the error disappears.

---

I'm not experienced enough to know whether I should just follow the advice and use `np.asarray(obj)`, or whether this needs a more targetted refactoring. Ensuring that the array is not copied seems important, so perhaps it's just a matter of treating scalars differently?

**Comment by loichuder** [comment]
Thanks for the report, I'll take a look.

Is is **only** for scalar datasets ? It does not happen for regular arrays ?

**Comment by axelboc** [comment]
Yep, more specifically **numeric** scalar datasets, which are the ones that are fetched as binary (with `format=bin`).

**Comment by loichuder** [comment]
Actually, running the tests shows that a lot of array/format combinations are involved...

As a rule of thumb, using `np.asarray` should be fine. Also, we have to remove the `copy=False` arg since it is visibly impossible to avoid copying when the argument is a scalar or a nested sequence (lists): https://numpy.org/devdocs/reference/generated/numpy.asarray.html#numpy.asarray

By using `copy=None` (the default behaviour), copy is avoided when possible (ex: when the argument is a numpy array) but allowed when there is no other choice (as I said, scalars and nested sequences)

**Comment by axelboc** [comment]
Couldn't `copy=None` potentially hide bugs, though? Should it be set to `None` conditionally, only for scalars?

**Comment by loichuder** [comment]
> Couldn't copy=None potentially hide bugs, though? 

I don't think so. At worst, you do a copy but the result is the same: your non-Numpy object (scalar value, nested sequences) is converted into a numpy array.

From what I gathered, the `copy=None` replicates the `copy=False` behaviour of `np.array` of numpy 1.x: a copy was silently done when dealing with non-Numpy object even with `copy=False`. Numpy 2.x now forbids this.

```
# Numpy 1.x
>>> a = 40049
>>> id(a)
140470620272336
>>> b = numpy.array(a, copy=False)
>>> id(b[()])
140470639816752
>>> id(b)
140470618765904

```

>  Should it be set to None conditionally, only for scalars?

The problem is not limited to scalars but also to nested sequences (ex: [[1,2], [3,4]]). Setting `None` conditionally for scalars and nested sequences would amount to the same result as setting `None` for all arguments types: scalars and nested sequences will be copied, numpy arrays will not.  

@t20100 Could you give a second opinion on this ?

**Comment by axelboc** [comment]
> From what I gathered, the copy=None replicates the copy=False behaviour of np.array of numpy 1.x: a copy was silently done when dealing with non-Numpy object even with copy=False. Numpy 2.x now forbids this.

Riiiight :joy_cat: 

![april-fools-joke](https://github.com/user-attachments/assets/1c9cd766-e425-4522-bb0c-e650801c4bfd)

**Comment by t20100** [comment]
I didn't had a close look, but it seems using `copy=None` keeps it simple, fixes the issue and keeps it working as it was.
